"""
Data loading and preprocessing for nvidia/OpenCodeReasoning.

DATASET STRUCTURE:
----------------─
nvidia/OpenCodeReasoning contains competitive programming solutions
generated by DeepSeek-R1 with execution verification.

Key fields:
  - input:  the problem statement
  - output: the expected output / test cases
  - solution: the code solution (Python)

We format each sample as a chat-style sequence:
  <|user|> Solve this problem: {input}
  <|assistant|> {solution}

This teaches the model to generate code solutions given problem descriptions.
"""

import torch
from datasets import load_dataset
from torch.utils.data import Dataset
from transformers import PreTrainedTokenizer


class OpenCodeReasoningDataset(Dataset):
    """
    Wraps nvidia/OpenCodeReasoning into tokenized training samples.

    Each sample becomes a single sequence:
        [system prompt] + [problem] + [solution] + [eos]

    The loss is computed only on the solution tokens (the assistant turn),
    not on the problem tokens. This is standard for instruction tuning -
    we don't want the model to learn to generate problem statements.
    """

    def __init__(
        self,
        tokenizer: PreTrainedTokenizer,
        max_seq_len: int = 4096,
        split: str = "split_0",
        max_samples: int | None = None,
    ):
        self.tokenizer = tokenizer
        self.max_seq_len = max_seq_len

        print(f"Loading nvidia/OpenCodeReasoning ({split})...")
        ds = load_dataset("nvidia/OpenCodeReasoning", split=split, trust_remote_code=True)

        if max_samples and max_samples < len(ds):
            ds = ds.select(range(max_samples))
            print(f"  Subsampled to {max_samples} examples")

        self.data = ds
        print(f"  Loaded {len(self.data)} examples")

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        row = self.data[idx]

        # Format as a chat conversation
        messages = [
            {
                "role": "user",
                "content": f"Solve this competitive programming problem:\n\n{row['input']}",
            },
            {
                "role": "assistant",
                "content": row["solution"],
            },
        ]

        # Use the tokenizer's chat template (Qwen3 has one built-in).
        # This handles special tokens, turn formatting, etc.
        text = self.tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=False
        )

        # Tokenize with truncation
        encoded = self.tokenizer(
            text,
            max_length=self.max_seq_len,
            truncation=True,
            padding=False,
            return_tensors=None,
        )

        input_ids = encoded["input_ids"]
        attention_mask = encoded["attention_mask"]

        # Build labels: mask out the user turn
        # We only compute loss on the assistant's response.
        # Find where the assistant turn starts by tokenizing just the user part.
        user_text = self.tokenizer.apply_chat_template(
            messages[:1], tokenize=False, add_generation_prompt=True
        )
        user_len = len(self.tokenizer(user_text, truncation=True, max_length=self.max_seq_len)["input_ids"])

        labels = list(input_ids)  # copy
        # Set user-turn tokens to -100 (ignored by CrossEntropyLoss)
        for i in range(min(user_len, len(labels))):
            labels[i] = -100

        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "labels": labels,
        }


def collate_fn(batch: list[dict], pad_token_id: int) -> dict:
    """
    Pads a batch of variable-length sequences to the same length.

    Right-pads input_ids and attention_mask with pad_token_id/0.
    Right-pads labels with -100 (ignored by CrossEntropyLoss).
    Right-padding is correct for training (left-padding is only needed
    for batch generation where the last real token position matters).

    """
    max_len = max(len(item["input_ids"]) for item in batch)

    input_ids = []
    attention_mask = []
    labels = []

    for item in batch:
        pad_len = max_len - len(item["input_ids"])
        input_ids.append(item["input_ids"] + [pad_token_id] * pad_len)
        attention_mask.append(item["attention_mask"] + [0] * pad_len)
        labels.append(item["labels"] + [-100] * pad_len)  # -100 = ignore index for CrossEntropyLoss

    return {
        "input_ids": torch.tensor(input_ids, dtype=torch.long),
        "attention_mask": torch.tensor(attention_mask, dtype=torch.long),
        "labels": torch.tensor(labels, dtype=torch.long),
    }
